root = "."
tmp_dir = "/tmp"

[build]
cmd = "go tool templ generate && go build -o /tmp/web ./cmd/web/web.go"
include_ext = ["go", "templ"]
include_file = [".env", "default.env"]
exclude_dir = []
exclude_regex = ["_test\\.go", "templates\\/.+_templ\\.go"]
send_interrupt = true
kill_delay = 1000000 # 1 ms in nanosec
stop_on_error = true
full_bin = "env $(sort -u -t '=' -k 1,1 .env default.env) /tmp/web" # merge .env into default.env
