services:
    mongo:
        image: mongo:8.0.9
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db
        environment:
            - TZ=Europe/Kyiv
        healthcheck:
            test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s

volumes:
    mongo_data: